steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'functions'
    - 'deploy'
    - 'pitch-summary'
    - '--runtime=python311'
    - '--trigger-http'
    - '--allow-unauthenticated'
    - '--entry-point=gcp_pitch_summary'
    - '--source=.'
    - '--region=us-central1'
    - '--project=baseball-summary'
substitutions:
  _BRANCH: master
