steps:
  - name: 'python:3.11-slim'
    id: 'test'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --no-cache-dir -r requirements.txt
        pip install pytest pytest-asyncio
        pytest tests/ --asyncio-mode=auto
    dir: '.'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    args:
      - 'functions'
      - 'deploy'
      - 'pitch-summary'
      - '--runtime=python311'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--entry-point=gcp_pitch_summary'
      - '--memory=512MB'
      - '--region=us-central1'
      - '--source=.'
    waitFor: ['test']
timeout: '20m'
options:
  logging: CLOUD_LOGGING_ONLY
